openapi: 3.0.3
info:
  title: Project Aurora Inter-Service API Contracts
  version: 0.1.0
  description: |
    Core inter-service interactions that coordinate the five microservices (M-API, O-API, C-API, S-API, A-API).
    Endpoints are described from the caller's perspective to ensure consistent contracts across services.
servers:
  - url: https://m-api.internal.aurora
    description: Management API (internal network)
  - url: https://o-api.internal.aurora
    description: Orchestration API (internal only)
  - url: https://c-api.aurora
    description: Content Delivery API (public edge)
  - url: https://s-api.internal.aurora
    description: Strategy API (internal only)
  - url: https://a-api.internal.aurora
    description: Analytics API (internal only)
paths:
  /orchestrate/run-blueprint:
    post:
      tags:
        - O-API
      summary: Trigger orchestration for a blueprint.
      description: M-API requests the O-API to execute a configured blueprint using a specific context and workflow inputs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunBlueprintRequest'
      responses:
        '202':
          description: Accepted for asynchronous execution.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunBlueprintResponse'
  /orchestrations/{orchestrationId}/status:
    get:
      tags:
        - O-API
      summary: Retrieve orchestration status and results.
      description: M-API polls the O-API for the lifecycle status of an orchestration job.
      parameters:
        - name: orchestrationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current orchestration state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrchestrationStatusResponse'
  /analytics/ingest:
    post:
      tags:
        - A-API
      summary: Ingest delivery analytics events.
      description: C-API posts delivery and consumption telemetry to A-API for analysis and agent detection.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyticsIngestRequest'
      responses:
        '202':
          description: Events accepted for processing.
  /analytics/agent-detections:
    post:
      tags:
        - A-API
      summary: Return agent detection feedback to C-API.
      description: A-API notifies C-API of detected AI agents for adaptive delivery strategies.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentDetectionFeedbackRequest'
      responses:
        '200':
          description: Feedback received and acknowledged.
  /strategy/new-suggestion:
    post:
      tags:
        - M-API
      summary: Persist new strategic suggestion.
      description: S-API pushes market-driven content suggestions into M-API for review and routing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StrategySuggestionRequest'
      responses:
        '201':
          description: Suggestion stored successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StrategySuggestionResponse'
  /management/billing/token-usage:
    post:
      tags:
        - M-API
      summary: Record token usage reported by O-API.
      description: O-API notifies M-API of aggregated token usage to support billing (F6).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenUsageNotification'
      responses:
        '204':
          description: Token usage recorded.
components:
  schemas:
    RunBlueprintRequest:
      type: object
      required:
        - blueprintId
        - orchestrationId
        - invokerUserId
      properties:
        blueprintId:
          type: integer
          format: int64
        orchestrationId:
          type: string
          description: Correlation identifier generated by M-API.
        invokerUserId:
          type: integer
          format: int64
        siteContextId:
          type: integer
          format: int64
        blueprintVersion:
          type: integer
        workflowOverrides:
          type: object
          additionalProperties: true
        executionMetadata:
          type: object
          additionalProperties: true
    RunBlueprintResponse:
      type: object
      required:
        - orchestrationId
        - status
      properties:
        orchestrationId:
          type: string
        status:
          type: string
          enum: [accepted, running, completed, failed]
        estimatedCompletionAt:
          type: string
          format: date-time
    OrchestrationStatusResponse:
      type: object
      required:
        - orchestrationId
        - status
      properties:
        orchestrationId:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed]
        resultPayload:
          type: object
          additionalProperties: true
        tokenUsage:
          $ref: '#/components/schemas/TokenUsageSummary'
        createdAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true
    AnalyticsIngestRequest:
      type: object
      required:
        - contentId
        - events
      properties:
        contentId:
          type: string
        blueprintId:
          type: integer
          format: int64
        siteContextId:
          type: integer
          format: int64
        deliveryChannel:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/AnalyticsEvent'
    AnalyticsEvent:
      type: object
      required:
        - eventType
        - occurredAt
      properties:
        eventType:
          type: string
        occurredAt:
          type: string
          format: date-time
        userAgent:
          type: string
        requestIp:
          type: string
          format: ipv4
        metadata:
          type: object
          additionalProperties: true
    AgentDetectionFeedbackRequest:
      type: object
      required:
        - contentId
        - detections
      properties:
        contentId:
          type: string
        detections:
          type: array
          items:
            type: object
            required:
              - agentName
              - confidence
            properties:
              analyticsLogId:
                type: integer
                format: int64
              agentName:
                type: string
              agentFamily:
                type: string
              confidence:
                type: number
                format: float
              guidance:
                type: string
    StrategySuggestionRequest:
      type: object
      required:
        - suggestionId
        - blueprintId
        - payload
      properties:
        suggestionId:
          type: string
        blueprintId:
          type: integer
          format: int64
        siteContextId:
          type: integer
          format: int64
        payload:
          type: object
          additionalProperties: true
        priority:
          type: integer
        suggestedFor:
          type: string
          format: date
    StrategySuggestionResponse:
      type: object
      required:
        - suggestionId
        - status
      properties:
        suggestionId:
          type: string
        status:
          type: string
          enum: [accepted, queued]
        createdAt:
          type: string
          format: date-time
    TokenUsageNotification:
      type: object
      required:
        - orchestrationId
        - userId
        - serviceTag
        - tokens
        - cost
      properties:
        orchestrationId:
          type: string
        userId:
          type: integer
          format: int64
        blueprintId:
          type: integer
          format: int64
        serviceTag:
          type: string
        tokens:
          $ref: '#/components/schemas/TokenUsageSummary'
        cost:
          type: object
          required:
            - amount
            - currency
          properties:
            amount:
              type: number
              format: double
            currency:
              type: string
              minLength: 3
              maxLength: 3
        billingMetadata:
          type: object
          additionalProperties: true
    TokenUsageSummary:
      type: object
      required:
        - total
      properties:
        total:
          type: integer
        input:
          type: integer
        output:
          type: integer
